export enum EnumActionEventAction {
  Download = "Download",
  Upload = "Upload",
  Edit = "Edit",
  Delete = "Delete",
  AddRole = "AddRole",
  RemoveRole = "RemoveRole",
  Duplicate = "Duplicate",
  Comment = "Comment",
  Share = "Share",
  Assign = "Assign",
  Star = "Star",
  Public = "Public",
  Private = "Private",
}
